import { Duration, RemovalPolicy, Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as s3n from 'aws-cdk-lib/aws-s3-notifications';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as nodejs from 'aws-cdk-lib/aws-lambda-nodejs';
import * as sqs from 'aws-cdk-lib/aws-sqs';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as logs from 'aws-cdk-lib/aws-logs';

// NOTE: All comments and descriptions in this IaC file are English only,
// per the project rule that forbids Japanese in CloudFormation/CDK output.

export interface SesNotifyStackProps extends StackProps {
  /**
   * Optional Secrets Manager secret ARN holding the SLACK_WEBHOOK_URL secret.
   * Granted read-only to the Lambda if provided.
   */
  readonly secretArn?: string;
  /**
   * Optional Secrets Manager secret id/name passed to the Lambda as an env var
   * (SECRETS_MANAGER_SECRET_ID) so configLoader fetches the secret at runtime.
   * Not a secret value itself.
   */
  readonly secretId?: string;
  /** Target receiving domain (non-secret operational value). */
  readonly targetDomain?: string;
}

export class SesNotifyStack extends Stack {
  constructor(scope: Construct, id: string, props: SesNotifyStackProps = {}) {
    super(scope, id, props);

    // 1st bucket: raw mail written by the SES receipt rule (configured manually
    // after deploy, pointing at this bucket's generated name).
    // Name is auto-generated by CloudFormation (no fixed name), so operators do
    // not supply RAW_MAIL_BUCKET; the generated name is injected into the Lambda
    // env below. SSE-S3 encryption at rest (NFR3.3) and full public access
    // block (NFR3.4).
    const rawMailBucket = new s3.Bucket(this, 'RawMailBucket', {
      encryption: s3.BucketEncryption.S3_MANAGED,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      enforceSSL: true,
      removalPolicy: RemovalPolicy.RETAIN,
    });

    // 2nd bucket: decoded/stored mail. Auto-generated name, same encryption and
    // access posture. The generated name is injected into the Lambda env below.
    const decodedMailBucket = new s3.Bucket(this, 'DecodedMailBucket', {
      encryption: s3.BucketEncryption.S3_MANAGED,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      enforceSSL: true,
      removalPolicy: RemovalPolicy.RETAIN,
    });

    // Dead-letter queue for the async Lambda invocation (FR5.3).
    // Items that still fail after retries land here for observability (NFR1.4 / NFR2.3).
    const deadLetterQueue = new sqs.Queue(this, 'DecodeDlq', {
      retentionPeriod: Duration.days(14),
      enforceSSL: true,
    });

    // Decode Lambda. Node.js LTS runtime, explicit timeout and memory sized for
    // the 10MB attachment limit (NFR4.1 / NFR4.2). esbuild bundles TypeScript.
    const decodeFunction = new nodejs.NodejsFunction(this, 'DecodeFunction', {
      runtime: lambda.Runtime.NODEJS_20_X,
      entry: 'src/handler.ts',
      handler: 'handler',
      timeout: Duration.seconds(60),
      memorySize: 512,
      logRetention: logs.RetentionDays.ONE_MONTH,
      // Standard asynchronous retry (default 2) with DLQ on exhaustion (NFR1.3).
      retryAttempts: 2,
      deadLetterQueueEnabled: true,
      deadLetterQueue,
      environment: {
        RAW_MAIL_BUCKET: rawMailBucket.bucketName,
        DECODED_MAIL_BUCKET: decodedMailBucket.bucketName,
        // Non-secret operational values are passed as plain env vars.
        // The SLACK_WEBHOOK_URL secret is resolved at runtime from Secrets
        // Manager and is never placed in the template. Only the secret's
        // id/name (not a secret value) is passed so configLoader can fetch it.
        ...(props.targetDomain ? { TARGET_DOMAIN: props.targetDomain } : {}),
        ...(props.secretId ? { SECRETS_MANAGER_SECRET_ID: props.secretId } : {}),
      },
    });

    // Trigger the Lambda on ObjectCreated in the 1st bucket (FR1.2).
    rawMailBucket.addEventNotification(
      s3.EventType.OBJECT_CREATED,
      new s3n.LambdaDestination(decodeFunction),
    );

    // Least-privilege IAM (NFR3.1):
    // - raw bucket: GetObject only (read the received raw mail).
    // - decoded bucket: GetObject (idempotency HeadObject/read) and PutObject (store) only.
    //   No delete, no list, no wildcard actions or resources.
    // - CloudWatch Logs is granted implicitly by the Lambda service role.
    decodeFunction.addToRolePolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['s3:GetObject'],
        resources: [rawMailBucket.arnForObjects('*')],
      }),
    );
    decodeFunction.addToRolePolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['s3:GetObject', 's3:PutObject'],
        resources: [decodedMailBucket.arnForObjects('*')],
      }),
    );
    // 冪等性チェックの HeadObject は、対象キーが存在しない場合 s3:ListBucket が無いと
    // 404 ではなく 403 (AccessDenied) を返す (S3 の仕様)。ListBucket をバケット本体に
    // 限定して付与し、存在しない新規キーで正しく 404 (= 未保存) と判定できるようにする。
    decodeFunction.addToRolePolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['s3:ListBucket'],
        resources: [decodedMailBucket.bucketArn],
      }),
    );

    // Grant read-only access to the specific secret, if provided (NFR3.1).
    if (props.secretArn) {
      decodeFunction.addToRolePolicy(
        new iam.PolicyStatement({
          effect: iam.Effect.ALLOW,
          actions: ['secretsmanager:GetSecretValue'],
          resources: [props.secretArn],
        }),
      );
    }
  }
}
